variable "aws_access_key" {
  description = "AWS access key"
}

variable "aws_secret_key" {
  description = "AWS secret access key"
}

variable "region" {
  description = "AWS region"
  default     = "us-west-2"
}
variable "admin_ip" {
    default = ""
}

variable "availability_zones" {
  description = "aws zones by region"
  default = {
    "us-east-1" = "us-east-1a,us-east-1c,us-east-1d"
    "us-west-2" = "us-west-2a,us-west-2b,us-west-2c"
    "eu-west-1" = "eu-west-1a,eu-west-1b,eu-west-1c"
  }
}

/* VPC settings */
variable "vpc_cidr" {
  description = "cidr for the whole vpc"
  default = "10.0.0.0/16"
}

variable "public_cidr_blocks" {
  description = "cidr for the public subnets"
  default = {
    "0" = "10.0.0.0/26"
    "1" = "10.0.0.64/26"
    "2" = "10.0.0.128/26"
  }
}

variable "private_cidr_blocks" {
  description = "cidr for the private subnets"
  default = {
    "0" = "10.0.10.0/26"
    "1" = "10.0.10.64/26"
    "2" = "10.0.10.128/26"
  }
}

/* Ubuntu 14.04 amis by region */
variable "amis" {
  description = "Base AMI to launch the instances with"
  default = {
    us-east-1 = "ami-2a0c313c"
    us-west-2 = "ami-5b4c5d22"
    eu-west-1 = "ami-30628649"
  }
}

/* Packer baked AMI */
variable "ami" {
  description = "AMI Generated by Packer"
  default = "ami-5b4c5d22"
}
